In [1]:
import numpy as np

Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. Будем считать, что температура в январе —t0 , то есть отсчёт индексов идёт с нуля.

In [6]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
print(f'Температура в июне {t[5]}')
t.min()
t[1]
t.max()
t[6]

Температура в июне 28


31

# Сложение и вычитание векторов

In [8]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(f'результат сложения {a + b}')
print(f'результат вычитания {a - b}')


результат сложения [15 23 14  8]
результат вычитания [ 5 -7 -4 -6]


# Умножение векторов

In [9]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

Задание 2.5
2 points possible (graded)
Ниже представлены доходы семьи за три месяца.

Доходы мужа: 120, 150 и 190 тысяч рублей.
Доходы жены: 130, 130 и 130 тысяч рублей.
Доходы тёщи: 2, 3 и 2.5 тысячи евро.
Вводите координаты полученных векторов через запятую (без пробела). Пример ввода ответа: 0,1,1.

Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.

In [11]:
husb = np.array([120, 150, 190])
wife = np.array([130, 130, 130])
grandma = np.array([2, 3, 2.5])
rate = 72
income_grandma=rate*grandma
income_grandma
all_income=husb+wife+income_grandma
all_income


array([394., 496., 500.])

# Линейная комбинация векторов

In [12]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

Задание 2.7

Найдите линейную комбинацию векторов  с коэффициентами 2, -3 и 5 соответственно.
Пример ввода ответа (через запятую, без пробелов): 0,1.

In [13]:
a = np.array([4, 5])
b = np.array([2, 1])
c = np.array([1, 0])
omega1 = 2
omega2 = -3
omega3 = 5
u=omega1*a + omega2*b + omega3*c
u

array([7, 7])

Задание 2.8

Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.
На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.
Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.
В качестве ответа введите координаты вектора через запятую, без пробелов. Пример ввода ответа: 0,1,1,1.

In [14]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])
omega1 = 200
omega2 = 400
income=omega2*b - omega1*a
income


array([-200, 1200,  200,  600])

# Cкалярное произведение векторов вычисляется при помощи функции np.dot()

In [15]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

In [16]:
a = np.array([4, 5, -1])
w = np.array([2, 0, 1])
np.dot(a, w)

7