In [30]:
import pandas as pd
import numpy as np

In [2]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Задание 5.1
Составьте матрицу  доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.
В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.
Примечание. После того как вы запишете векторы в numpy.array, не забудьте его транспонировать, иначе доходы каждого из членов семьи Ивановых запишутся в строки исходной матрицы.

In [24]:
income=np.array([[100,220,140], [150,200,130], [90,80,100]])
incomeT=income.T
incomeT

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Задание 5.2
Составьте матрицу  Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.
В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.
Примечание. После того как вы запишете векторы в numpy.array, не забудьте его транспонировать, иначе расходы каждого из членов семьи Ивановых запишутся в строки исходной матрицы.

In [15]:
Cons=np.array([[50,50,60], [100,80,140], [100,20,140]])
ConsT=Cons.T
ConsT

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Задание 5.3
Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.
Используйте полученную ранее матрицу , где доходы расположены по столбцам.
Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

In [25]:
net_income=incomeT-0.13*incomeT
net_income

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Задание 5.4
Вычислите матрицу , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [26]:
balance=net_income-ConsT
balance

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [33]:
A = np.matrix("1, -1, 2, 4, 0; 8, 2, 0, 5, 3; 0, 1, 2, 1, 2")
B = np.matrix("1, 0, 1, 0; 0, 0, 2, -1; 1, 0, 1, 1; 0, 1, 1, 1; 1, 1, 0, -1")
np.dot(A, B)


matrix([[ 3,  4,  5,  7],
        [11,  8, 17,  0],
        [ 4,  3,  5,  0]])

In [39]:
A = np.matrix("1, 2, 1; 1, -1, 2")
AT=A.transpose()
G = AT * A
G

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

Задание 7.1
Найдите произведение матрицы  и вектора 

In [42]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
np.dot(A, x)

array([26, 30])

Задание 7.2
Даны две матрицы:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
Найдите произведение матриц в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [46]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
np.dot(B, A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

Задание 7.3
Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
Составьте матрицу , расположив векторы , ,  в строках. Найдите матрицу Грама  (матрицу скалярных произведений столбцов матрицы ) системы векторов , , .

Чему равна полученная матрица Грама ?

In [52]:
#x = np.array([1,2,1,0,4])
#y = np.array([2,1,-1,1,0])
#z = np.array([-1,1,-1,0,0])
A=np.matrix("1,2,1,0,4; 2,1,-1,1,0; -1,1,-1,0,0")
AT=A.transpose()
G=AT*A
G

matrix([[ 6,  3,  0,  2,  4],
        [ 3,  6,  0,  1,  8],
        [ 0,  0,  3, -1,  4],
        [ 2,  1, -1,  1,  0],
        [ 4,  8,  4,  0, 16]])

УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Задание 7.4
Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.
Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).
Выберите координаты вектора прибыли салона:

In [54]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [100]:
count=Count_DF.values
price=Price_DF.values
count=count.T
price=price.T
income=count*price
clear=np.dot(com, income)
clear
income

array([[20. ,  3.6, 24. ,  7.2, 15. , 50. , 24.2, 31.5],
       [ 7.5, 52.5, 24. ,  9.6, 87.5, 15. ,  1. ,  0. ],
       [12. ,  3. ,  0. , 50.4, 54. ,  6. ,  6. , 77.5],
       [12. , 25. , 15. , 11.2, 25. , 34. , 12.5, 31. ],
       [10. ,  6. ,  8. , 10. , 27. , 30. , 34. , 56. ]])

In [108]:
A=income[0]
B=income[1]
C=income[2]
D=income[3]
E=income[4]


income1=A+B+C+D+E
income_still=income1-clear
income_still


array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [110]:
A=np.matrix("2, 0, 0; 0, 1, 0; 0, 0, 4")
print(np.linalg.det(A))

7.999999999999998


In [112]:
A_1=np.linalg.inv(A)
print(np.linalg.det(A_1))

0.12500000000000003


In [113]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
B=np.linalg.inv(A)
B

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
Задание 10.2
Найдите ранг системы векторов , , , . Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [119]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A=np.array([v1, v2, v3, v4]).T
print(np.linalg.matrix_rank(A))


4


Задание 10.4
1 point possible (graded)
Найдите матрицу Грама системы векторов , , , : . В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [122]:
AT=A.T
G=np.dot(AT, A)
G

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

Задание 10.5
1 point possible (graded)
Найдите определитель матрицы Грама  системы , , , . Ответ округлите до целого числа.

In [123]:
print(np.linalg.det(G))

3716647.9999999995


Задание 10.7
Найдите обратную матрицу к матрице Грама  системы , , , . В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [124]:
G_1=np.linalg.inv(G)
G_1

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [129]:
v1=np.array([-1, 2, -7, 9]).T
v2=np.array([2, 8, 2, -1]).T
np.dot(v1, v2)

-9

In [130]:
A=np.matrix("1, 1; 1, 2")
G=A.T@A
G

matrix([[2, 3],
        [3, 5]])

In [132]:
A=np.matrix("1, 2; 3, 7")
np.linalg.inv(A)

matrix([[ 7., -2.],
        [-3.,  1.]])

In [140]:
A=np.matrix("2, 3, 8; 10, 2, 14; -2, -2, -6")
np.linalg.matrix_rank(A)

2

In [143]:
A=np.matrix("1, 2; -3, 1; 1, 2; 1, -1")
AT=A.T
G=np.dot(AT, A)
G

matrix([[12,  0],
        [ 0, 10]])

In [151]:
Ginv=np.linalg.inv(G)
Ginv

matrix([[0.08333333, 0.        ],
        [0.        , 0.1       ]])

In [152]:
b=np.array([1, 4, 5, 0])
bT=b.T
ATb=np.dot(AT, bT)
ATb

matrix([[-6, 16]])

In [154]:
w=Ginv*ATb
w

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)