In [1]:
import pandas as pd
import numpy as np

In [2]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [3]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [4]:
Hut_Paradise_values

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

In [5]:
room5=Hut_Paradise_values[4]
room5

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [6]:
floors=Hut_Paradise_values[:,3]
floors

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [7]:
area=Hut_Paradise_values[:,1]
liv_area=Hut_Paradise_values[:,5]
noliv_area=area-liv_area
noliv_area

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [12]:
a=np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
# вектор из единиц
b=np.ones(9)
a1=a*14
#c=np.dot(a1,b)
a1

array([140, 280, 420, 210,  70, 560, 280, 112, 280])

In [14]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

d=2*v+(-3)*w
print('linear combination:',d)

linear combination: [-3 14  3  4  2]


In [17]:
r=np.dot(u,d)
r

0